META_DATA_PATH = 'table_meta_data'
PAGE_DIRECTORY_PATH = 'page_directory'
INDEX_DIRECTORY_PATH = 'index'

INDIRECTION_COLUMN = 0
RID_COLUMN = 1
TIMESTAMP_COLUMN = 2
SCHEMA_ENCODING_COLUMN = 3

BUFFER_POOL_CAPACITY = 16
RECORDS_PER_PAGE = 512
PAGE_RANGE_MAX_LEN = 64
NUM_META_COLUMNS = 4