META_DATA_PATH = 'table_meta_data'
PAGE_DIRECTORY_PATH = 'page_directory'
INDEX_DIRECTORY_PATH = 'index'
DISK_DIRECTORY_PATH = 'disk'

INDIRECTION_COLUMN = 0
RID_COLUMN = 1
TPS_COLUMN = 2
SCHEMA_ENCODING_COLUMN = 3

BUFFER_POOL_CAPACITY = 64
RECORDS_PER_PAGE = 512
PAGE_RANGE_MAX_LEN = 64
NUM_META_COLUMNS = 4

PAGE_SIZE = 4096
PAGE_SIZE_WITH_META_DATA = 4112
RECORD_SIZE = 8

B_TREE_ORDER = 3